#include "ET1202_SFR.h"
#include "XSFR_GLOBAL.h"
#include "main.h"
#include "Gpio.h"

void GPIO_Init (void)
{
	PINSET1 = PINSET1_REGS;
	PINSET2 = PINSET2_REGS;
	PINSET3 = PINSET3_REGS;
	PINSET4 = PINSET4_REGS;
	PINSET5 = PINSET5_REGS;
	PINSET6 = PINSET6_REGS;
	PINSET7 = PINSET7_REGS;
	
	PINCONG1 = PINCONG1_REGS;
	PINCONG2 = PINCONG2_REGS;
	PINCONG3 = PINCONG3_REGS;
	PINCONG4 = PINCONG4_REGS;
	PINCONG5 = PINCONG5_REGS;
	PINCONG6 = PINCONG6_REGS;
	PINCONG7 = PINCONG7_REGS;
}