#include "ET1202_SFR.h"
#include "XSFR_GLOBAL.h"
#include "main.h"
#include "OCP.h"

void OCP_Init (void)
{
	AOCPCONT = AOCPCONT_REGS;
	OCPCONT = OCPCONT_REGS | OCPC;
	
//	AOCPCONT = AOCPEN | AOCP_LEVEL_VOLTAGE_015;
//	AOCPCONT = AOCPEN | AOCP_LEVEL_VOLTAGE_02;
//	AOCPCONT = AOCPEN | AOCP_LEVEL_VOLTAGE_025;
//	AOCPCONT = AOCPEN | AOCP_LEVEL_VOLTAGE_03;
//	AOCPCONT = AOCPEN | AOCP_LEVEL_VOLTAGE_035;
//	AOCPCONT = AOCPEN | AOCP_LEVEL_VOLTAGE_04;
//	AOCPCONT = AOCPEN | AOCP_LEVEL_VOLTAGE_045;
//	AOCPCONT = AOCPEN | AOCP_LEVEL_VOLTAGE_05;
	
//	AOCPCONT = DOCPEN | AOCPEN | AOCP_LEVEL_VOLTAGE_015;
//	AOCPCONT = DOCPEN | AOCPEN | AOCP_LEVEL_VOLTAGE_02;
//	AOCPCONT = DOCPEN | AOCPEN | AOCP_LEVEL_VOLTAGE_025;
//	AOCPCONT = DOCPEN | AOCPEN | AOCP_LEVEL_VOLTAGE_03;
//	AOCPCONT = DOCPEN | AOCPEN | AOCP_LEVEL_VOLTAGE_035;
//	AOCPCONT = DOCPEN | AOCPEN | AOCP_LEVEL_VOLTAGE_04;
//	AOCPCONT = DOCPEN | AOCPEN | AOCP_LEVEL_VOLTAGE_045;
//	AOCPCONT = DOCPEN | AOCPEN | AOCP_LEVEL_VOLTAGE_05;

//	OCPCONT = OCPC | OCPDBT | OCPMS;//User Mode
}